//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForteReports.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BRepTimerOn {
            get {
                return ((bool)(this["BRepTimerOn"]));
            }
            set {
                this["BRepTimerOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bHourRepCheck {
            get {
                return ((bool)(this["bHourRepCheck"]));
            }
            set {
                this["bHourRepCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bShiftOneCheck {
            get {
                return ((bool)(this["bShiftOneCheck"]));
            }
            set {
                this["bShiftOneCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bShiftTwoCheck {
            get {
                return ((bool)(this["bShiftTwoCheck"]));
            }
            set {
                this["bShiftTwoCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bShiftThreeCheck {
            get {
                return ((bool)(this["bShiftThreeCheck"]));
            }
            set {
                this["bShiftThreeCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bDayRepCheck {
            get {
                return ((bool)(this["bDayRepCheck"]));
            }
            set {
                this["bDayRepCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10/27/2021 14:25:00")]
        public global::System.DateTime ShiftOneTime {
            get {
                return ((global::System.DateTime)(this["ShiftOneEnd"]));
            }
            set {
                this["ShiftOneEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10/27/2021 14:25:00")]
        public global::System.DateTime ShiftTwoTime {
            get {
                return ((global::System.DateTime)(this["ShiftTwoEnd"]));
            }
            set {
                this["ShiftTwoEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10/27/2021 14:26:00")]
        public global::System.DateTime ShiftThreeTime {
            get {
                return ((global::System.DateTime)(this["ShiftThreeTime"]));
            }
            set {
                this["ShiftThreeTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10/27/2021 14:26:00")]
        public global::System.DateTime ProdDayEnd {
            get {
                return ((global::System.DateTime)(this["ProdDayEnd"]));
            }
            set {
                this["ProdDayEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int iScanRate {
            get {
                return ((int)(this["iScanRate"]));
            }
            set {
                this["iScanRate"] = value;
            }
        }
    }
}
